import { useState, useEffect } from "react";
import { getJiraTickets, getJiraStats } from "../services/api";

const PRI_COLOR = {
  critical: "bg-red-900/40 text-red-300 border-red-700",
  high:     "bg-red-900/40 text-red-300 border-red-700",
  medium:   "bg-yellow-900/40 text-yellow-300 border-yellow-800",
  low:      "bg-green-900/40 text-green-300 border-green-700",
};
const ESC_COLOR = {
  "Escalate":     "bg-red-900/40 text-red-300 border-red-700",
  "Auto-Resolve": "bg-green-900/40 text-green-300 border-green-700",
};

function Badge({ label, colorMap, fallback = "bg-gray-800 text-gray-400 border-gray-600" }) {
  const cls = colorMap[label] ?? fallback;
  return <span className={`px-2 py-0.5 rounded-full text-xs font-semibold border ${cls}`}>{label}</span>;
}

function StatCard({ title, value, color }) {
  const colors = {
    blue:   "bg-blue-900/30 border-blue-700 text-blue-400",
    green:  "bg-green-900/30 border-green-700 text-green-400",
    red:    "bg-red-900/30 border-red-700 text-red-400",
    purple: "bg-purple-900/30 border-purple-700 text-purple-400",
  };
  return (
    <div className={`rounded-xl border p-5 shadow-sm ${colors[color] ?? colors.blue}`}>
      <p className="text-sm font-medium text-gray-400">{title}</p>
      <p className="text-3xl font-bold mt-1 text-white">{value ?? "—"}</p>
    </div>
  );
}

export default function JiraPage() {
  const [tickets, setTickets] = useState([]);
  const [stats,   setStats]   = useState(null);
  const [loading, setLoading] = useState(true);
  const [skip,    setSkip]    = useState(0);
  const LIMIT = 50;

  const fetchAll = async (s = 0) => {
    setLoading(true);
    try {
      const [t, st] = await Promise.all([getJiraTickets(s, LIMIT), getJiraStats()]);
      setTickets(t.data);
      setStats(st.data);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchAll(skip); }, [skip]);

  return (
    <div className="bg-gray-950 min-h-screen">
    <div className="p-6 space-y-6 pb-10">

      <div>
        <h1 className="text-2xl font-bold text-white">Jira Integration</h1>
        <p className="text-gray-400 text-sm mt-1">Simulated Jira tickets auto-generated by the Multi-Agent Workflow</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard title="Total Jira Tickets" value={stats?.total}        color="blue"   />
        <StatCard title="Open"               value={stats?.open}         color="purple" />
        <StatCard title="Auto-Resolved"      value={stats?.auto_resolved} color="green"  />
        <StatCard title="Escalated"          value={stats?.escalated}    color="red"    />
      </div>

      {/* Table */}
      <div className="bg-gray-900 rounded-xl border border-gray-700 shadow-sm">
        <div className="px-5 py-4 border-b border-gray-700">
          <h2 className="text-sm font-semibold text-gray-300">All Jira Tickets</h2>
        </div>

        {loading ? (
          <p className="text-gray-400 text-sm p-5">Loading…</p>
        ) : tickets.length === 0 ? (
          <div className="text-center py-16 space-y-3">
            <p className="text-4xl">🎫</p>
            <p className="text-white font-semibold">No Jira tickets yet</p>
            <p className="text-gray-400 text-sm">Run the Multi-Agent Workflow to generate Jira records.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead className="bg-gray-800 text-gray-400 uppercase text-xs">
                <tr>
                  {["Jira ID", "Title", "Category", "Priority", "Severity", "Team", "Escalation", "Status", "Created"].map(h => (
                    <th key={h} className="px-4 py-3 text-left font-semibold whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-700">
                {tickets.map(t => (
                  <tr key={t.jira_id} className="hover:bg-gray-800 transition-colors">
                    <td className="px-4 py-2 text-blue-400 font-mono text-xs font-semibold">{t.jira_id}</td>
                    <td className="px-4 py-2 text-gray-200 max-w-xs truncate font-medium">{t.title}</td>
                    <td className="px-4 py-2 text-gray-400 whitespace-nowrap">{t.category}</td>
                    <td className="px-4 py-2"><Badge label={t.priority} colorMap={PRI_COLOR} /></td>
                    <td className="px-4 py-2 text-gray-400">{t.severity}</td>
                    <td className="px-4 py-2 text-gray-300 whitespace-nowrap text-xs">{t.assigned_team}</td>
                    <td className="px-4 py-2"><Badge label={t.escalation_status} colorMap={ESC_COLOR} /></td>
                    <td className="px-4 py-2">
                      <span className="px-2 py-0.5 rounded-full text-xs font-semibold border bg-blue-900/40 text-blue-300 border-blue-800">
                        {t.status}
                      </span>
                    </td>
                    <td className="px-4 py-2 text-gray-400 text-xs whitespace-nowrap">
                      {t.created_at ? new Date(t.created_at).toLocaleString() : "—"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Pagination */}
      {tickets.length > 0 && (
        <div className="flex gap-3">
          <button
            disabled={skip === 0}
            onClick={() => setSkip(Math.max(0, skip - LIMIT))}
            className="px-4 py-2 text-sm bg-gray-800 border border-gray-700 text-gray-300 rounded-lg disabled:opacity-40 hover:bg-gray-700"
          >← Prev</button>
          <button
            disabled={tickets.length < LIMIT}
            onClick={() => setSkip(skip + LIMIT)}
            className="px-4 py-2 text-sm bg-gray-800 border border-gray-700 text-gray-300 rounded-lg disabled:opacity-40 hover:bg-gray-700"
          >Next →</button>
        </div>
      )}
    </div>
    </div>
  );
}
